apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-k8s-kustomize
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ruchabhange/kustomize.git
    targetRevision: HEAD
    path: 
   
  destination:
    server: https://kubernetes.default.svc
    namespace: kustomize
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
